### ISSUE TITLE
Bug: inkycal_calendar -> KeyError: 31

### ISSUE THREAD

**Issue by RFNajera** [aceisace/Inkycal#168]
**Describe the bug**
The calendar module was loading fine for days until minutes past midnight today. Then it started throwing an error:

```python
01-02-2021 00:01:50 | main |  ERROR: Exception in module 1
Traceback (most recent call last):
  File "/home/pi/Inkycal/inkycal/main.py", line 279, in run
    black,colour=module.generate_image()
  File "/home/pi/Inkycal/inkycal/modules/inkycal_calendar.py", line 263, in generate_image
    grid[days],
KeyError: 31
```
**Desktop (please complete the following information):**
Raspberry pi 3A+
Raspbian (latest release)
Waveshare 7.5-inch black and white e paper display (v2)
Inkycal 2.0

**Comment by hag2k** [comment]
Hi,
I had the same problem. I added the following check to  /home/pi/Inkycal/inkycal/modules/inkycal_calendar.py , line 260
It solves the problem for now, maybe there is a better longterm solution.

 ```
for days in days_with_events:
        if days in grid:    <----
          draw_border(
            im_colour,
            grid[days],
            (icon_width, icon_height),
            radius = 6,
            thickness= 1,
            shrinkage = (0.4, 0.2)
            )
```

**Comment by aceisace** [comment]
I still can't reproduce this error even after using several different iCalendars. The tests for the calendar module seem to be running fine too. I pushed [this commit](https://github.com/aceisace/Inkycal/commit/948573cb59b7bb86c8075f1a2d721ea49f171942#diff-66e66a31bd89160b6b4ab3d23aa2f1eeb3eb229d3755248c50d6acfd59f7b965) on 22nd Nov 2020, which should have fixed the issue. It's possible you are using a less-up-to date version of the calendar module.


In either case, before I push a hotfix, could you please run the following command:
```bash
cd /home/$USER/Inkycal/inkycal/modules && mv inkycal_calendar.py inkycal_calendar_old.py && wget https://raw.githubusercontent.com/aceisace/Inkycal/main/inkycal/modules/inkycal_calendar.py
```
Then restart Inkycal. If the issue is still not resolved, please let me know. Thanks in advance.

**Comment by RFNajera** [comment]
Tried your way, Aceisace, here's the result:

```
pi@inkycalrpi:~ $ python3 inky_run.py
yfinance is not installed! Please install with:
pip3 install yfinance
inkycal_calendar loaded
inkycal_weather loaded
inkycal_feeds loaded
loaded inkycal
Inkycal version: v2.0.0
Selected E-paper display: epd_7_in_5_v2
generating image(s) for Calendar - Show monthly calendar with events from iCalendars...Error!
Traceback (most recent call last):
  File "/home/pi/Inkycal/inkycal/main.py", line 226, in test
    black,colour=module.generate_image()
  File "/home/pi/Inkycal/inkycal/modules/inkycal_calendar.py", line 263, in generate_image
    grid[days],
KeyError: 31

generating image(s) for Weather (openweathermap) - Get weather forecasts from openweathermap...OK!
generating image(s) for RSS / Atom - Display feeds from given RSS/ATOM feeds...OK!
Error/s in modules: 1
Inkycal version: v2.0.0
Selected E-paper display: epd_7_in_5_v2
Date: 2 Feb 21 | Time: 17:33
```

**Comment by RFNajera** [comment]
hag2k's fix up there fixed it.
```
pi@inkycalrpi:~ $ python3 inky_run.py
yfinance is not installed! Please install with:
pip3 install yfinance
inkycal_calendar loaded
inkycal_weather loaded
inkycal_feeds loaded
loaded inkycal
Inkycal version: v2.0.0
Selected E-paper display: epd_7_in_5_v2
generating image(s) for Calendar - Show monthly calendar with events from iCalendars...OK!
generating image(s) for Weather (openweathermap) - Get weather forecasts from openweathermap...OK!
generating image(s) for RSS / Atom - Display feeds from given RSS/ATOM feeds...OK!
Inkycal version: v2.0.0
Selected E-paper display: epd_7_in_5_v2
Date: 2 Feb 21 | Time: 17:43
Generating images for all modules...successful
Initialising..Updating display......Done
Sending E-Paper to deep sleep...Done

No errors since 1 display updates 
program started a minute ago
16 minutes left until next refresh
```

**Comment by aceisace** [comment]
@RFNajera Thanks for testing the the code. Looks like the hotfix was needed. I've implemented the exact suggestion as hag2k . 
Thanks for the report @RFNajera and thanks for the code snippet @hag2k !
