### ISSUE TITLE
Start of inky_run.py fails after Manual installation

### ISSUE THREAD

**Issue by martinklein** [aceisace/Inkycal#213]
I did a manual installation and received the following error after running inky_run:

Python 3.9.2 (/usr/bin/python3)
>>> %cd /home/pi/Inkycal
>>> %Run inky_run.py
Traceback (most recent call last):
  File "/home/pi/Inkycal/inky_run.py", line 1, in <module>
    from inkycal import Inkycal # Import Inkycal
  File "/home/pi/Inkycal/inkycal/__init__.py", line 5, in <module>
    import inkycal.modules.inkycal_agenda
  File "/home/pi/Inkycal/inkycal/modules/__init__.py", line 8, in <module>
    from .inkycal_stocks import Stocks
  File "/home/pi/Inkycal/inkycal/modules/inkycal_stocks.py", line 23, in <module>
    import yfinance as yf
  File "/home/pi/.local/lib/python3.9/site-packages/yfinance/__init__.py", line 23, in <module>
    from .ticker import Ticker
  File "/home/pi/.local/lib/python3.9/site-packages/yfinance/ticker.py", line 27, in <module>
    import pandas as _pd
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa:F401
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 48 from C header, got 40 from PyObject

Many thanks for your suggestions

**Comment by martinklein** [comment]
My numpy is on version 1.19.5

Regards Martin

**Comment by martinklein** [comment]
Updated to latest numpy and now it works.
